import LegalPageLayout from "@/components/LegalPageLayout";

const PrivacyPolicyPage = () => {
	return (
		<LegalPageLayout
			title="Privacy Policy"
			description="Read Eko's privacy policy to understand how we collect, use, and protect your personal information."
		>
			<p>
				<strong>
					This document is an electronic record in terms of Information
					Technology Act, 2000 and rules made there under as applicable. This
					electronic record is generated by a computer system and does not
					require any physical or digital signatures.
				</strong>
			</p>
			<p>
				<strong>Eko Bharat Ventures Private Limited</strong> (formerly known as
				Eko India Financial Services Private Limited), a company incorporated
				under the Companies Act, 1956 having its registered office at 547,
				Mandakini Enclave, Alaknanda, New Delhi – 110019 and corporate office at
				68, Phase IV, Udyog Vihar, Sector 18, Gurugram, Haryana 122015
				(hereinafter referred to as "Eko") owns and operates{" "}
				<a href="https://eko.in">https://eko.in</a> ("Website/Platform").
			</p>
			<p>
				At Eko, data protection is a matter of trust and your privacy is very
				important to us. We use your personal information only in the manner as
				set out in this Privacy Policy.
			</p>
			<p>
				<strong>Note:</strong> Our privacy policy is subject to changes at any
				time without notice. Please review this policy periodically.
			</p>

			<h4>1. Your Privacy</h4>
			<p>
				At Eko, we are extremely proud of our commitment to protect your
				privacy. We value your trust in us.
			</p>
			<p>
				<strong>Eko Privacy Assurance:</strong> We promise that we will not sell
				or rent your personal information to third parties or use the same for
				unsolicited emails or messages without your explicit consent.
			</p>

			<h4>2. Information that Eko Collects</h4>
			<p>
				When you use our Platform/Website or services, we collect and store your
				personal information in order to record, support and facilitate your
				participation in the services. The information can also be used for
				sending periodic emails announcing important service changes, new
				features, technical issue updates and news.
			</p>

			<h4>3. Information Collected by Eko</h4>
			<p>
				Eko collects Users' personal information to provide services. These
				include, but are not limited to: name, mailing address, telephone
				numbers, email addresses, credit card information, aadhaar card
				information and other information needed for providing the services. We
				also collect non-personally identifiable information including referral
				URLs, IP addresses, browser information, etc.
			</p>

			<h4>4. Our Use of Your Information</h4>
			<p>
				We use your personal information to facilitate the Services you request.
				We do not sell, rent, trade or exchange any personally-identifying
				information of our Users. We may provide your collected information to
				our affiliates and service providers under contract to support the
				operation of the Platform.
			</p>

			<h4>5. Disclosure of Information</h4>
			<ul>
				<li>
					Any disclosure of information to third party will be on the prior
					permission of yours.
				</li>
				<li>
					We will not request prior permission where you have agreed for
					disclosure by way of contract earlier.
				</li>
				<li>
					We will not request prior permission in cases for complying legal
					requirements.
				</li>
			</ul>

			<h4>6. Security</h4>
			<p>
				To protect your privacy and security, we always use industry-standard
				encryption technologies when transferring and receiving user data. We
				abide by the security standards provided under the Information
				Technology Act, 2000.
			</p>

			<h4>7. Advertisements on Website</h4>
			<p>
				We use third-party advertising companies to serve ads when you visit our
				Website. These companies may use your information (not including your
				name, address, email address, or telephone number) about your visits to
				provide advertisements about services of interest to you.
			</p>

			<h4>8. Links to Other Sites</h4>
			<p>
				Our Website may contain links to other websites. Eko is not responsible
				for the privacy practices or the content of those linked websites.
			</p>

			<h4>9. Amendments</h4>
			<p>
				Eko reserves the right to revise its policies at any time without prior
				notice.
			</p>

			<h4>10. Nodal Desk</h4>
			<p>
				Nodal Desk – Monday to Friday from 10:00 a.m. to 6:00 p.m – Eko Bharat
				Ventures Private Limited, 68, Phase IV, Udyog Vihar, Sector 18,
				Gurugram, Haryana 122015.
			</p>
			<p>
				Email us your suggestions / queries / complaints at{" "}
				<a href="mailto:cs@eko.co.in">cs@eko.co.in</a>.
			</p>

			<p className="uppercase text-sm mt-8">
				YOU ACKNOWLEDGE AND AGREE THAT ANY DISPUTE OVER PRIVACY IS SUBJECT TO
				THE TERMS AND CONDITIONS OF THIS PRIVACY POLICY. YOU AND WE EACH SUBMIT
				TO THE EXCLUSIVE JURISDICTION OF THE INDIAN COURTS AT DELHI.
			</p>
		</LegalPageLayout>
	);
};

export default PrivacyPolicyPage;
